export const KEYS = {
    MIL_WAREHOUSES: 'MIL_WAREHOUSES',
    COMP_WAREHOUSES: 'COMP_WAREHOUSES',
    MILITARY_UNIT: 'MILITARY_UNIT',
    MILITARY_UNITS: 'MILITARY_UNITS',
    VEHICLE_INSURANCE_HISTORY: 'VEHICLE_INSURANCE_HISTORY',
    VEHICLE_REPARATION_HISTORY: 'VEHICLE_REPARATION_HISTORY',
    VEHICLE_TRANSFER_HISTORY: 'VEHICLE_TRANSFER_HISTORY',
    SETTINGS: 'SETTINGS',
    NOTIFICATION_SETTINGS: 'NOTIFICATION_SETTINGS',
    VEHICLE: 'VEHICLE',
    VEHICLE_CARD: 'VEHICLE_CARD',
    VEHICLE_CARDS: 'VEHICLE_CARDS',
    VEHICLE_IRREVERSIBLE_LOSS: 'VEHICLE_IRREVERSIBLE_LOSS',
    NOTIFICATIONS: 'NOTIFICATIONS',
    UNREAD_NOTIFICATIONS_COUNT: 'UNREAD_NOTIFICATIONS_COUNT',
    INVENTORIES: 'INVENTORIES',
    INVENTORY: 'INVENTORY'
} as const;
